### ISSUE TITLE
O2 Card Reader Not Working

### ISSUE THREAD

**Issue by mandresve** [lietxia/XiaoXinAir14IML_2019_hackintosh#29]
Hi, I have recently adapted this EFI configuration to my S540 system and almost everything works successfully. However the microsd card reader does not work (O2 Card Reader). Is there any way to make it work? Any idea where the problem is? Thanks in advance.

**Comment by mandresve** [comment]
Problem solved with O2 Card Reader.
I can confirm that on a MacBookPro8,2 running 12.3 that the SDXC controller no longer supports SD card detection. In addition, I've verified that 11.6.1 does have functional SDXC so this issue is limited from Monterey to Ventura.

This issue doesn't affect Ivy Bridge and newer Macs with SDXC controllers (Sandy and newer use the 14e4:16bc chipsets). This leads me to believe that when MacBookPro18,x was added since Monterey, Apple implemented VT-D mapping similar to the Broadcom BCM5701 and Intel i210 situation.

While a bit strange this wasn't implemented in Big Sur (AppleSDXC was already compiled for the arm64e target), some engineer probably realized this when reworking the SDXC stack for the 14"/16" systems. 

With regards to resolving this, we'll simply out-probe AppleSDXC with an older variant without the VT-D enforcement. Add CtlnaSDXC.kext to your existing configuration and that's all.

[CtlnaSDXC-v1.0.0.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/11182520/CtlnaSDXC-v1.0.0.zip)

**Comment by mandresve** [comment]
[CtlnaSDXC-v1.0.0.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/11182520/CtlnaSDXC-v1.0.0.zip)

**Comment by CelestialSayuki** [comment]
macOS can successfully detect this card reader now, but I find that it can’t read any sd card.

**Comment by CelestialSayuki** [comment]
I'll further test it tomorrow, seems not working now

**Comment by mandresve** [comment]
> macOS can successfully detect this card reader now, but I find that it can’t read any sd card.

- In this case, can you confirm that CtlnaSDXC.kext is loaded and working? Funny enough, in my machine, MacOS Ventura cannot display the card reader info under System Info > Card Reader, but it's loaded under PCI (Installed driver: yes).

- Is the PCI Slot correct under Devices section? I double checked it using IORegistryExplorer

- Additionally, I disabled the Realtek-based kexts, but seems working fine with and without them.

![Screenshot](https://user-images.githubusercontent.com/18217976/230783186-68cbf900-ac35-4eeb-92c7-19c85f2d8144.jpg)

**Comment by CelestialSayuki** [comment]
> > macOS can successfully detect this card reader now, but I find that it can’t read any sd card.
> 
> In this case, can you confirm that CtlnaSDXC.kext is loaded and working? Funny enough, in my machine, MacOS Ventura cannot display the card reader info under System Info > Card Reader, but it's loaded under PCI (Installed driver: yes). Is the PCI Slot correct under Devices section? Additionally, I disabled the Realtek-based kexts, but seems working fine with and without it.

I have the same situation on macOS Monterey, card reader is empty but it is displayed in PCI info. I’ve confirmed that it’s loaded but doesn’t work, I’ll check it again tomorrow.

**Comment by mandresve** [comment]
Any update? I tested on two S540 machines and the patch for O2 Card Reader seems to work under Ventura.

**Comment by CelestialSayuki** [comment]
Still not work, I’ll reinstall macOS and try again.

**Comment by mandresve** [comment]
Please let me know if you need to test further on this :)

**Comment by CelestialSayuki** [comment]
![截屏2023-04-17 21 45 50](https://user-images.githubusercontent.com/50404193/232503013-4cf252dc-e005-446a-b4db-546ce7db183c.png)
![截屏2023-04-17 21 46 45](https://user-images.githubusercontent.com/50404193/232503145-353c6b6f-fced-4b28-ad8a-a4375024da61.png)
![截屏2023-04-17 21 46 57](https://user-images.githubusercontent.com/50404193/232503200-1872fc30-ac19-46f9-b0df-13a529dfa293.png)
Still not working
I haven't update to OC 0.9.1, I'll update as soon as I finish backing up my phone

**Comment by mandresve** [comment]
Could you please attach screen capture showing the full path & info under IORegistryExplorer? Like in this one:

> ![Screenshot](https://user-images.githubusercontent.com/18217976/230783186-68cbf900-ac35-4eeb-92c7-19c85f2d8144.jpg)

**Comment by CelestialSayuki** [comment]
![截屏2023-04-17 21 57 03](https://user-images.githubusercontent.com/50404193/232506063-af94d799-2a4e-418e-a086-dfc391f58d9e.png)
Oh, should I change my model to MacBook Pro?

**Comment by mandresve** [comment]
IDK if that makes a difference. I have doubts if your machine have the O2 card reader variant. It seems to, but if so, it should be working...
Mine as reference:
![Captura de pantalla 2023-04-17 a la(s) 9 01 16 a m](https://user-images.githubusercontent.com/18217976/232507456-2c381e0a-ec4f-4146-8d7f-e3c591eeb7c4.png)

Under the device, is "vendor-id" and "subsystem-id" the same as above?

**Comment by CelestialSayuki** [comment]
> IDK if that makes a difference. I have doubts if your machine have the O2 card reader variant. It seems to, but if so, it should be working... Mine as reference: ![Captura de pantalla 2023-04-17 a la(s) 9 01 16 a m](https://user-images.githubusercontent.com/18217976/232507456-2c381e0a-ec4f-4146-8d7f-e3c591eeb7c4.png)
> 
> Under the device, is "vendor-id" and "subsystem-id" the same as above?

My card reader hardware is broken, I’ll try to fix it

**Comment by CelestialSayuki** [comment]
![IMG_0018](https://user-images.githubusercontent.com/50404193/232684143-9f073823-c1b3-4a22-87ef-5f4e48c9092d.jpeg)

Fixed, here got water, so I clean it up

**Comment by CelestialSayuki** [comment]
Strange, windows and bios can detect the sd card,  but still don’t work on macOS. I’ll change my model.

**Comment by CelestialSayuki** [comment]
Still not work after changing model to mpb16,3

**Comment by CelestialSayuki** [comment]
Fixed. The motherboard of this laptop has a very poor electrostatic shielding, so this screw cannot be tightened. If it is tightened, it will interfere with the SD card reader.
![7a0bf42b4c9220babb410b19482c37d1](https://user-images.githubusercontent.com/50404193/232697837-32a940e1-119d-4e3d-8db3-939ea104fd1e.jpg)

**Comment by mandresve** [comment]
I never thought about the possibility of a hardware failure, I'm glad it worked!

**Comment by CelestialSayuki** [comment]
@mandresve Can you test this? 
[BigSurSDXC-v1.0.0.zip](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/files/12281709/BigSurSDXC-v1.0.0.zip)

**Comment by mandresve** [comment]
@win1010525 

Tested. KEXT works correctly in Ventura 13.5 (22G74). All SDXC capacities are supported without any problems. O2 reader.

![Captura de pantalla 2023-08-07 a la(s) 12 10 22 p m](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/assets/18217976/9faa63d7-7d06-4b88-af9c-eadac773d945)

**Comment by mandresve** [comment]
Now in Ventura 13.6.6 The card reader stopped working suddenly... searching for a fix!
![image](https://github.com/lietxia/XiaoXinAir14IML_2019_hackintosh/assets/18217976/b5afa4d6-bc74-40b4-9d60-f2d6ac42a166)
